### PR TITLE
Add python3 support for this plugin.

### LINKED ISSUE #15: Need Python3 Support
Macvim在开启py3支持的时候，会自动关闭py2的支持，作者可否考虑增加py3的支持呢？

### PR DESCRIPTION
**Pull request by ketor**
Signed-off-by: KetorD <d.ketor@gmail.com>

Fix #15

### CODE REVIEW

**Comment by ketor** [comment]
@ianva Please review. Thanks!

**Comment by ianva** [comment]
I'm afraid, I can't merge this code because it‘s unmaintainable.

You can create a util method like `superEncode`, it encapsulate  difference from python2 and python3,  and then `superEncode` is used to replace `String.encode` for originally code.

**Comment by ketor** [comment]
@ianva Refactored the py2/py3 compatibility code now. 
Please review. 
Thanks!

**Comment by ketor** [comment]
Add 4 new methods: `str_encode`, `str_decode`, `bytes_decode`, `url_quote`.
Now all py2/py3 compatibility processing is in these methods, so the main code logic is clear.

**Comment by ketor** [comment]
Tested on my mac with vim(+python) and MacVim(+python3).

**Pull request merged**
